// Copyright (C) 2025-2026 Marco Iannacone
// SPDX-License-Identifier: AGPL-3.0-only
/*
 * JOSHUA Terminal build script. No runtime dependencies; uses Node's fs and
 * child_process (git) only.
 *
 * Produces a deterministic dist/ tree (except for intentionally variable
 * metadata: build timestamp and git commit/branch):
 *
 *   dist/standalone/                         — standalone single-document app
 *   dist/pippo.com/human-systems/interactive-fiction/joshua/   — EN pippo tree
 *   dist/pippo.com/it/human-systems/interactive-fiction/joshua/ — IT pippo tree
 *   dist/build-info.json                     — build metadata
 *
 * The standalone build is a straight copy of src/ (minus src/dev/). The
 * pippo.com builds are the same copy plus a generated buildConfig.js that
 * configures language/navigation; game.js reads window.JOSHUA_BUILD when
 * present (see src/app/game.js). No deployment, no upload, no credentials.
 */
'use strict';

const fs = require('node:fs');
const path = require('node:path');
const { execSync } = require('node:child_process');

const ROOT = path.join(__dirname, '..');
const SRC = path.join(ROOT, 'src');
const DIST = path.join(ROOT, 'dist');

// Directories under src/ that must not ship in any build.
const EXCLUDE_DIRS = new Set(['dev']);

function version() {
  return JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8')).version;
}

function gitShort(args) {
  try {
    return execSync(`git ${args}`, { cwd: ROOT, encoding: 'utf8' }).trim();
  } catch (err) {
    return '';
  }
}

function rmrf(p) {
  fs.rmSync(p, { recursive: true, force: true });
}

function copyDir(srcDir, destDir) {
  fs.mkdirSync(destDir, { recursive: true });
  for (const entry of fs.readdirSync(srcDir, { withFileTypes: true })) {
    if (entry.name.startsWith('.')) continue;
    const s = path.join(srcDir, entry.name);
    const d = path.join(destDir, entry.name);
    if (entry.isDirectory()) {
      if (EXCLUDE_DIRS.has(entry.name)) continue;
      copyDir(s, d);
    } else {
      fs.copyFileSync(s, d);
    }
  }
}

function writeBuildConfig(destDir, config) {
  const js =
    '// Generated by tools/build.js. Deployment configuration for the pippo.com\n' +
    '// build; the standalone build ships no such file. See src/app/game.js.\n' +
    'window.JOSHUA_BUILD = ' + JSON.stringify(config, null, 2) + ';\n';
  fs.writeFileSync(path.join(destDir, 'buildConfig.js'), js);
}

function injectBuildConfigScript(htmlPath) {
  const marker = '<script src="app/game.js"></script>';
  const html = fs.readFileSync(htmlPath, 'utf8');
  if (html.includes('buildConfig.js')) return;
  fs.writeFileSync(htmlPath, html.replace(marker, '<script src="buildConfig.js"></script>\n  ' + marker));
}

// --- Public SEO / semantic metadata for the pippo.com builds only. ---
// The standalone build keeps the source HTML's EN title/description and no
// canonical/hreflang/OG/JSON-LD (it has no authoritative public URL).
const PIPPOP_ORIGIN = 'https://www.pippo.com';
const SEO_EN_URL = PIPPOP_ORIGIN + '/human-systems/interactive-fiction/joshua/';
const SEO_IT_URL = PIPPOP_ORIGIN + '/it/human-systems/interactive-fiction/joshua/';

const SEO = {
  en: {
    lang: 'en',
    title: 'JOSHUA — An Interactive WarGames Tribute by Marco Iannacone',
    description: 'JOSHUA is an open-source interactive web application by Marco Iannacone, created as a tribute to the 1983 film WarGames and as a reminder that not every decision that can be delegated to machines should be.',
    jsonldDescription: 'JOSHUA is an open-source interactive web application created by Marco Iannacone as a tribute to the 1983 film WarGames, which helped shape his professional path, and as a reminder that not every decision that can be delegated to machines should be.',
    url: SEO_EN_URL
  },
  it: {
    lang: 'it',
    title: 'JOSHUA — Un tributo interattivo a WarGames di Marco Iannacone',
    description: 'JOSHUA è una web app interattiva open source realizzata da Marco Iannacone come tributo al film WarGames del 1983 e come promemoria che non ogni decisione delegabile alle macchine dovrebbe esserlo.',
    jsonldDescription: 'JOSHUA è una web app interattiva open source realizzata da Marco Iannacone come tributo al film WarGames del 1983, che ha contribuito a orientare il suo percorso professionale, e come promemoria che non ogni decisione delegabile alle macchine dovrebbe esserlo.',
    url: SEO_IT_URL
  }
};

function structuredData(seo) {
  return {
    '@context': 'https://schema.org',
    '@type': 'SoftwareApplication',
    'name': 'JOSHUA',
    'applicationCategory': 'GameApplication',
    'operatingSystem': 'Web',
    'isAccessibleForFree': true,
    'author': { '@type': 'Person', 'name': 'Marco Iannacone' },
    'description': seo.jsonldDescription,
    'url': seo.url,
    'inLanguage': seo.lang,
    'license': 'https://www.gnu.org/licenses/agpl-3.0.html',
    'softwareVersion': version(),
    'keywords': 'WarGames, interactive fiction, human-machine decision making, automation'
  };
}

// JSON-LD is emitted inline. A <script type="application/ld+json"> element is a
// non-executable "data block" (not JavaScript), so it does not trigger CSP
// script-src enforcement — verified in Chromium and WebKit. The strict
// default-src 'self' CSP therefore stays intact with no 'unsafe-inline' and no
// hash.
function seoBlock(seo) {
  const jsonld = JSON.stringify(structuredData(seo));
  return [
    `<link rel="canonical" href="${seo.url}">`,
    `<link rel="alternate" hreflang="en" href="${SEO_EN_URL}">`,
    `<link rel="alternate" hreflang="it" href="${SEO_IT_URL}">`,
    `<link rel="alternate" hreflang="x-default" href="${SEO_EN_URL}">`,
    `<meta property="og:type" content="website">`,
    `<meta property="og:title" content="${seo.title}">`,
    `<meta property="og:description" content="${seo.description}">`,
    `<meta property="og:url" content="${seo.url}">`,
    `<meta property="og:site_name" content="pippo.com">`,
    '<script type="application/ld+json">' + jsonld + '</script>'
  ].join('\n  ');
}

function injectSeoMetadata(htmlPath, seo) {
  let html = fs.readFileSync(htmlPath, 'utf8');
  html = html.replace(/<title>[^<]*<\/title>/, `<title>${seo.title}</title>`);
  html = html.replace(/<meta name="description" content="[^"]*">/, `<meta name="description" content="${seo.description}">`);
  if (seo.lang === 'it') {
    html = html.replace('<html lang="en">', '<html lang="it">');
  }
  html = html.replace('<!-- SEO_META -->', seoBlock(seo));
  fs.writeFileSync(htmlPath, html);
}

function buildStandalone() {
  const dest = path.join(DIST, 'standalone');
  copyDir(SRC, dest);
  return dest;
}

function buildPippo() {
  const enDir = path.join(DIST, 'pippo.com', 'human-systems', 'interactive-fiction', 'joshua');
  const itDir = path.join(DIST, 'pippo.com', 'it', 'human-systems', 'interactive-fiction', 'joshua');

  copyDir(SRC, enDir);
  copyDir(SRC, itDir);

  // English tree: boots English, switches to the Italian path, returns to "/".
  writeBuildConfig(enDir, {
    lang: 'en',
    langHref: '/it/human-systems/interactive-fiction/joshua/index.html',
    returnHref: '/',
    returnLabel: 'RETURN TO PIPPO.COM PERSONAL OPERATING SYSTEM'
  });
  // Italian tree: boots Italian, switches to the English path, returns to "/it/".
  writeBuildConfig(itDir, {
    lang: 'it',
    langHref: '/human-systems/interactive-fiction/joshua/index.html',
    returnHref: '/it/',
    returnLabel: 'TORNA AL PERSONAL OPERATING SYSTEM DI PIPPO.COM'
  });

  injectBuildConfigScript(path.join(enDir, 'index.html'));
  injectBuildConfigScript(path.join(itDir, 'index.html'));

  // Localized SEO/semantic metadata (title, description, canonical, hreflang,
  // Open Graph, inline JSON-LD) for the public pippo.com pages.
  injectSeoMetadata(path.join(enDir, 'index.html'), SEO.en);
  injectSeoMetadata(path.join(itDir, 'index.html'), SEO.it);

  return [enDir, itDir];
}

function writeBuildInfo(buildTypes) {
  const info = {
    version: version(),
    commit: gitShort('rev-parse --short HEAD'),
    builtAt: new Date().toISOString(),
    buildTypes: buildTypes,
    branch: gitShort('rev-parse --abbrev-ref HEAD')
  };
  fs.mkdirSync(DIST, { recursive: true });
  fs.writeFileSync(path.join(DIST, 'build-info.json'), JSON.stringify(info, null, 2) + '\n');
  return info;
}

function packageStandalone() {
  const standalone = path.join(DIST, 'standalone');
  if (!fs.existsSync(path.join(standalone, 'index.html'))) {
    throw new Error('dist/standalone not built — run "node tools/build.js build" first');
  }
  const archive = path.join(DIST, `joshua-${version()}.tar.gz`);
  execSync(`tar -czf "${archive}" -C "${standalone}" .`, { cwd: ROOT, stdio: 'inherit' });
  return archive;
}

function main() {
  const command = process.argv[2] || 'build';
  switch (command) {
    case 'clean':
      rmrf(DIST);
      console.log('Removed dist/');
      return;
    case 'standalone':
      rmrf(DIST);
      buildStandalone();
      writeBuildInfo(['standalone']);
      console.log('Built dist/standalone/');
      return;
    case 'pippo':
      rmrf(DIST);
      buildPippo();
      writeBuildInfo(['pippo.com']);
      console.log('Built dist/pippo.com/ (EN + IT)');
      return;
    case 'package':
      console.log('Packaged ' + packageStandalone());
      return;
    case 'build':
      rmrf(DIST);
      buildStandalone();
      buildPippo();
      const info = writeBuildInfo(['standalone', 'pippo.com']);
      console.log('Built dist/standalone/');
      console.log('Built dist/pippo.com/ (EN + IT)');
      console.log('Wrote dist/build-info.json');
      return;
    default:
      console.error('Unknown command: ' + command);
      process.exit(1);
  }
}

main();
